const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
};

type InstacartLineItem = {
  name?: string;
  display_text?: string;
  quantity?: number;
  unit?: string;
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { title, lineItems, partnerLinkbackUrl } = await req.json();

    const INSTACART_API_KEY = Deno.env.get('INSTACART_API_KEY');
    if (!INSTACART_API_KEY) {
      return new Response(
        JSON.stringify({ success: false, error: 'Instacart export is not configured yet.' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
      );
    }

    const apiBaseUrl = (Deno.env.get('INSTACART_API_BASE_URL') || 'https://connect.dev.instacart.tools').replace(/\/+$/, '');

    const cleanTitle = typeof title === 'string' && title.trim() ? title.trim() : 'Munch Grocery List';
    const cleanLineItems = Array.isArray(lineItems)
      ? (lineItems as InstacartLineItem[])
          .map((item) => {
            const name = String(item?.name || '').trim();
            if (!name) return null;

            const nextItem: Record<string, unknown> = { name };

            const displayText = String(item?.display_text || '').trim();
            if (displayText) nextItem.display_text = displayText;

            const quantity = Number(item?.quantity);
            if (Number.isFinite(quantity) && quantity > 0) nextItem.quantity = quantity;

            const unit = String(item?.unit || '').trim();
            if (unit) nextItem.unit = unit;

            return nextItem;
          })
          .filter((item): item is Record<string, unknown> => Boolean(item))
          .slice(0, 100)
      : [];

    if (cleanLineItems.length === 0) {
      return new Response(
        JSON.stringify({ success: false, error: 'At least one grocery item is required.' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
      );
    }

    const payload: Record<string, unknown> = {
      title: cleanTitle,
      link_type: 'shopping_list',
      expires_in: 30,
      instructions: ['Generated by Munch. Review quantities before checkout.'],
      line_items: cleanLineItems,
      landing_page_configuration: {
        enable_pantry_items: true,
      },
    };

    if (typeof partnerLinkbackUrl === 'string' && partnerLinkbackUrl.trim()) {
      payload.landing_page_configuration = {
        ...(payload.landing_page_configuration as Record<string, unknown>),
        partner_linkback_url: partnerLinkbackUrl.trim(),
      };
    }

    const response = await fetch(`${apiBaseUrl}/idp/v1/products/products_link`, {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        Authorization: `Bearer ${INSTACART_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
    });

    const responseText = await response.text();
    const responseData = responseText ? JSON.parse(responseText) : null;

    if (!response.ok) {
      const message =
        (typeof responseData?.message === 'string' && responseData.message.trim()) ||
        (typeof responseData?.error === 'string' && responseData.error.trim()) ||
        'Instacart export failed.';
      console.error('create-instacart-shopping-list error:', response.status, responseText);
      return new Response(
        JSON.stringify({ success: false, error: message, details: responseData }),
        { status: response.status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
      );
    }

    const productsLinkUrl =
      typeof responseData?.products_link_url === 'string' ? responseData.products_link_url.trim() : '';

    if (!productsLinkUrl) {
      return new Response(
        JSON.stringify({ success: false, error: 'Instacart did not return a shopping link.' }),
        { status: 502, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
      );
    }

    return new Response(
      JSON.stringify({ success: true, productsLinkUrl }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Instacart export failed.';
    console.error('create-instacart-shopping-list error:', message);
    return new Response(
      JSON.stringify({ success: false, error: message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
    );
  }
});
