-- Generated by scripts/jsonl_to_recipes_sql.py
-- Source JSONL: data/wikibooks_cookbook_recipes_v4.sample.jsonl

begin;

insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  '''Out of Salad Dressing'' Salad Dressing',
  '',
  '30 min',
  'Beginner',
  ARRAY['1 ½ lemons , juiced', '1 cup freshly grated Parmesan cheese', '2 teaspoons garlic salt', '¾ cup mayonnaise', '1 cup milk']::text[],
  ARRAY['salad dressing', 'lemon juice', 'mayonnaise', 'milk', 'parmesan', 'garlic salt', 'lunch', 'savory', 'umami', 'fresh/citrusy']::text[],
  ARRAY['Mix together lemon juice, Parmesan cheese, garlic salt, and mayonnaise until smooth.', 'Stir in milk, adjusting the amount or adding a little water, to make the dressing as thin or thick as you like.', 'Cover and refrigerate 8 hours, or overnight.']::text[],
  'community-seed',
  'e280c6c4-4c73-4085-9851-634f69bc7e68'::uuid,
  'https://en.wikibooks.org/wiki/Cookbook:''Out_of_Salad_Dressing''_Salad_Dressing',
  'munch',
  null,
  12,
  true,
  '{"import_type": "wikibooks_cookbook", "original_title": "''Out of Salad Dressing'' Salad Dressing", "servings_text": "12", "prep_time": null, "cook_time": null, "total_time": null, "source_dataset": "Wikibooks Cookbook", "source_url": "https://en.wikibooks.org/wiki/Cookbook:''Out_of_Salad_Dressing''_Salad_Dressing", "raw_tags": ["salad dressing", "lemon juice", "mayonnaise", "milk", "parmesan", "garlic salt"], "normalized_app_tags": ["salad dressing", "lemon juice", "mayonnaise", "milk", "parmesan", "garlic salt", "lunch", "savory", "umami", "fresh/citrusy"], "chef_profile_url": "/chef/e280c6c4-4c73-4085-9851-634f69bc7e68"}'::jsonb
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower('''Out of Salad Dressing'' Salad Dressing')
     or (
       'https://en.wikibooks.org/wiki/Cookbook:''Out_of_Salad_Dressing''_Salad_Dressing' is not null
       and lower(coalesce(existing.source_url, '')) = lower('https://en.wikibooks.org/wiki/Cookbook:''Out_of_Salad_Dressing''_Salad_Dressing')
     )
);

insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  '1-2-3-4 Cake',
  '',
  '30 min',
  'Advanced',
  ARRAY['1 cup (240 g / 8.5 oz ) butter', '1 cup (240 ml / 8.1 oz) milk', '1 teaspoon vanilla extract', '2 cups (450 g / 16 oz) white granulated sugar', '3 cups (400 g / 14 oz) all-purpose flour', '3 teaspoons baking powder', '3 pinches of salt', '4 eggs']::text[],
  ARRAY['cake', 'with images', 'easy', 'featured', 'vegetarian', 'butter', 'egg', 'dessert', 'baking powder', 'white sugar', 'all-purpose flour', 'cow milk', 'breakfast', 'lunch', 'sweet']::text[],
  ARRAY['Preheat oven to 175 °C (350 °F)', 'Cream the butter and sugar together until fluffy.', 'Beat in the vanilla and eggs, one at a time, ensuring the batter is well mixed after each egg.', 'Gradually sift in the dry ingredients, alternating with small additions of the milk.', 'Transfer to a greased and floured baking pan .', 'Bake at 175 °C (350 °F), until a skewer inserted shows no moist crumbs.', 'You will need these things', 'The ingredients. (Salt not shown here)', 'Cooking implements: beaters, large bowl, cup measurement and large cake tin. Scales optional.', 'An oven, of course!', '1. Preheat your oven.', '2. Cream the butter and sugar together.', '3. Crack the eggs in, and beat them in too', 'After beating in the eggs, it looks like this', '4. Now get your flour and milk', '5. Mix a little bit of flour in it.', '6. Then a little bit of milk.', 'Repeat 5 and 6 until done. By now the mixture will be very smooth.', '7. Pour the mixture into a greased and floured cake tin, then pop it in the oven', '8. Checking if the cake is "done": put a sharp knife or skewer into the centre of the cake', 'If the knife is dirty - the mixture is still wet - put it back in! (This was after about 15 minutes, it takes a lot longer)', 'Finally, it''s done! Notice how brown the top is, due to the high sugar content']::text[],
  'community-seed',
  'e280c6c4-4c73-4085-9851-634f69bc7e68'::uuid,
  'https://en.wikibooks.org/wiki/Cookbook:1-2-3-4_Cake',
  'munch',
  null,
  8,
  true,
  '{"import_type": "wikibooks_cookbook", "original_title": "1-2-3-4 Cake", "servings_text": "8–10", "prep_time": null, "cook_time": null, "total_time": null, "source_dataset": "Wikibooks Cookbook", "source_url": "https://en.wikibooks.org/wiki/Cookbook:1-2-3-4_Cake", "raw_tags": ["cake", "with images", "easy", "featured", "vegetarian", "butter", "egg", "dessert", "baking powder", "white sugar", "all-purpose flour", "cow milk"], "normalized_app_tags": ["cake", "with images", "easy", "featured", "vegetarian", "butter", "egg", "dessert", "baking powder", "white sugar", "all-purpose flour", "cow milk", "breakfast", "lunch", "sweet"], "chef_profile_url": "/chef/e280c6c4-4c73-4085-9851-634f69bc7e68"}'::jsonb
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower('1-2-3-4 Cake')
     or (
       'https://en.wikibooks.org/wiki/Cookbook:1-2-3-4_Cake' is not null
       and lower(coalesce(existing.source_url, '')) = lower('https://en.wikibooks.org/wiki/Cookbook:1-2-3-4_Cake')
     )
);

insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  '20-Minute Beef Stroganoff',
  '',
  '30 min',
  'Intermediate',
  ARRAY['8 oz (230 g) wide egg noodles (figures are for yolk-free noodles)', '1 teaspoon olive oil', '1 package (8 oz/230 g) sliced mushrooms', '1 large (1 cup /150 g/5.3 oz) coarsely- chopped onion', '1 package (17 oz/480 g) prepared beef tips with gravy', '¼ cup (60 ml/2.0 US fl oz) skim milk', '1 can (10.75 oz/305 g) condensed cream of mushroom soup (figures are for fat-free)', 'Salt to taste', 'Pepper to taste', '1 teaspoon bottled minced garlic', '¼ teaspoon (or more to taste) mild or hot paprika', '½ cup (250 ml/8.5 US fl oz) sour cream (figures are for reduced-fat)', '¼ cup (125 g/4.4 oz) finely-chopped fresh parsley']::text[],
  ARRAY['beef', 'easy', 'inexpensive', 'mushroom', 'onion', 'pasta and noodles', 'boiled', 'main course', 'garlic', 'skim milk', 'breakfast', 'lunch', 'dinner', 'spicy', 'savory', 'umami', 'fresh/citrusy']::text[],
  ARRAY['Prepare noodles according to package directions and drain.', 'As the noodles are boiling, warm oil in very deep skillet or Dutch oven over medium heat.', 'Add mushrooms and onions and cook until onion is soft, about 3 minutes.', 'Add beef tips, milk, and mushroom soup.', 'Add salt and pepper to taste and stir well.', 'Reduce heat to simmer and stir in garlic, paprika, and sour cream.', 'Simmer lightly, without letting it boil (that will curdle it).', 'When noodles are finished and drained, serve with noodles on serving plate or individual plates, with sauce over it.', 'Garnish with parsley.']::text[],
  'community-seed',
  'e280c6c4-4c73-4085-9851-634f69bc7e68'::uuid,
  'https://en.wikibooks.org/wiki/Cookbook:20-Minute_Beef_Stroganoff',
  'munch',
  null,
  4,
  true,
  '{"import_type": "wikibooks_cookbook", "original_title": "20-Minute Beef Stroganoff", "servings_text": "4", "prep_time": null, "cook_time": null, "total_time": null, "source_dataset": "Wikibooks Cookbook", "source_url": "https://en.wikibooks.org/wiki/Cookbook:20-Minute_Beef_Stroganoff", "raw_tags": ["beef", "easy", "inexpensive", "mushroom", "onion", "pasta and noodles", "boiled", "main course", "garlic", "skim milk"], "normalized_app_tags": ["beef", "easy", "inexpensive", "mushroom", "onion", "pasta and noodles", "boiled", "main course", "garlic", "skim milk", "breakfast", "lunch", "dinner", "spicy", "savory", "umami", "fresh/citrusy"], "chef_profile_url": "/chef/e280c6c4-4c73-4085-9851-634f69bc7e68"}'::jsonb
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower('20-Minute Beef Stroganoff')
     or (
       'https://en.wikibooks.org/wiki/Cookbook:20-Minute_Beef_Stroganoff' is not null
       and lower(coalesce(existing.source_url, '')) = lower('https://en.wikibooks.org/wiki/Cookbook:20-Minute_Beef_Stroganoff')
     )
);

insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  '40 Cloves in a Roast Chicken',
  '',
  '30 min',
  'Intermediate',
  ARRAY['1 ea . (3–4 pounds ) broiler/fryer chicken', '¼ cup Country Roast Chicken Seasoning', '40 cloves garlic , smashed', 'Olive oil', '1 large lemon , thinly sliced', '½ bunch thyme', '5 sprigs rosemary', '½ bunch flat-leaf parsley']::text[],
  ARRAY['medium difficulty', 'without servings', 'garlic', 'whole chicken', 'lemon', 'thyme', 'rosemary', 'parsley', 'dinner', 'savory', 'fresh/citrusy']::text[],
  ARRAY['Rub the Country Roast Chicken Seasoning under the skin of the chicken. Refrigerate for at least 1 hour.', 'Tie the chicken''s legs together and wing tips under the back with butcher''s twine.', 'Heat garlic in a microwave on low for 6 minutes.', 'In this step, work quickly. If using a bag, place garlic in and stuff it in the cavity. If not, just stuff it in.', 'Coat chicken with olive oil. Place herbs in the bottom of a roasting pan and put lemon slices on top.', 'Put chicken breast side up on top and bake in an oven for 45 minutes at 375°F (190°C).', 'Turn the temperature up to 425°F (220°C) and bake for 45 more minutes or until the internal temperature in both the thigh and breast reaches 165°F (75°C) and the juices run clear.', 'Let rest for 10 minutes and serve.']::text[],
  'community-seed',
  'e280c6c4-4c73-4085-9851-634f69bc7e68'::uuid,
  'https://en.wikibooks.org/wiki/Cookbook:40_Cloves_in_a_Roast_Chicken',
  'munch',
  null,
  4,
  true,
  '{"import_type": "wikibooks_cookbook", "original_title": "40 Cloves in a Roast Chicken", "servings_text": null, "prep_time": null, "cook_time": null, "total_time": null, "source_dataset": "Wikibooks Cookbook", "source_url": "https://en.wikibooks.org/wiki/Cookbook:40_Cloves_in_a_Roast_Chicken", "raw_tags": ["medium difficulty", "without servings", "garlic", "whole chicken", "lemon", "thyme", "rosemary", "parsley"], "normalized_app_tags": ["medium difficulty", "without servings", "garlic", "whole chicken", "lemon", "thyme", "rosemary", "parsley", "dinner", "savory", "fresh/citrusy"], "chef_profile_url": "/chef/e280c6c4-4c73-4085-9851-634f69bc7e68"}'::jsonb
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower('40 Cloves in a Roast Chicken')
     or (
       'https://en.wikibooks.org/wiki/Cookbook:40_Cloves_in_a_Roast_Chicken' is not null
       and lower(coalesce(existing.source_url, '')) = lower('https://en.wikibooks.org/wiki/Cookbook:40_Cloves_in_a_Roast_Chicken')
     )
);

insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  'A Nice Cup of Tea',
  '',
  '30 min',
  'Intermediate',
  ARRAY['32 fl oz (1 L) hot water', '3–5 measures of loose tea leaves or 3–5 tea bags', 'Sweetener , such as sugar or honey , to taste', 'Milk or lemon juice to taste']::text[],
  ARRAY['beverage', 'with images', 'very easy', 'without servings', 'irish', 'english', 'tea', 'naturally gluten-free', 'vegetarian', 'easy', 'tea and tisanes', 'lemon juice', 'cow milk', 'dessert', 'spicy', 'sweet', 'fresh/citrusy', 'gluten-free']::text[],
  ARRAY['Pour freshly-drawn water into a tea kettle, and heat it to your desired temperature. An electric kettle is fast and convenient.', 'Pour some hot tap water into your teapot and let stand for about several seconds to a minute to pre-warm it. Alternately, you can swish some of the hotter boiling water from your kettle around in the teapot for a few seconds. Pour out this water before adding the tea to the teapot.', 'If using loose tea, place it into an infuser, then into the teapot. If using teabags, place them into the teapot.', 'When the water reaches the preferred temperature, pour it from the tea kettle into the teapot. As you pour, try to avoid pouring directly onto the tea (especially important for green and white teas) to avoid scalding the leaves.', 'Allow the tea to infuse quietly (i.e. do not stir the teapot or "dunk the teabag"). Agitating the tea releases more of the bitter compounds and degrades the taste. Watch the time to avoid over-infusion, and remove the infuser or tea bag when the time is up.', 'Pour tea into your cup(s). Add sweetener and milk or lemon to taste.']::text[],
  'community-seed',
  'e280c6c4-4c73-4085-9851-634f69bc7e68'::uuid,
  'https://en.wikibooks.org/wiki/Cookbook:A_Nice_Cup_of_Tea',
  'munch',
  null,
  1,
  true,
  '{"import_type": "wikibooks_cookbook", "original_title": "A Nice Cup of Tea", "servings_text": "1 pot of tea", "prep_time": null, "cook_time": null, "total_time": null, "source_dataset": "Wikibooks Cookbook", "source_url": "https://en.wikibooks.org/wiki/Cookbook:A_Nice_Cup_of_Tea", "raw_tags": ["beverage", "with images", "very easy", "without servings", "irish", "english", "tea", "naturally gluten-free", "vegetarian", "easy", "tea and tisanes", "lemon juice", "cow milk"], "normalized_app_tags": ["beverage", "with images", "very easy", "without servings", "irish", "english", "tea", "naturally gluten-free", "vegetarian", "easy", "tea and tisanes", "lemon juice", "cow milk", "dessert", "spicy", "sweet", "fresh/citrusy", "gluten-free"], "chef_profile_url": "/chef/e280c6c4-4c73-4085-9851-634f69bc7e68"}'::jsonb
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower('A Nice Cup of Tea')
     or (
       'https://en.wikibooks.org/wiki/Cookbook:A_Nice_Cup_of_Tea' is not null
       and lower(coalesce(existing.source_url, '')) = lower('https://en.wikibooks.org/wiki/Cookbook:A_Nice_Cup_of_Tea')
     )
);

insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  'Aadun (Nigerian Corn Flour with Palm Oil)',
  '',
  '30 min',
  'Beginner',
  ARRAY['1 cup corn flour', '¼ cup palm oil', '½ teaspoon chile pepper', '½ teaspoon salt']::text[],
  ARRAY['cs1 maint numeric names authors list', 'with images', 'easy', 'without servings', 'without cooking time', 'yoruba', 'chile', 'corn flour', 'palm oil', 'salt', 'lunch', 'spicy']::text[],
  ARRAY['Combine the corn flour, palm oil, chili pepper, and salt in a bowl.', 'Leave the mixture to sit for 2–3 hours.', 'Shape the mixture as desired, and serve with drinks.']::text[],
  'community-seed',
  'e280c6c4-4c73-4085-9851-634f69bc7e68'::uuid,
  'https://en.wikibooks.org/wiki/Cookbook:Aadun_(Nigerian_Corn_Flour_with_Palm_Oil)',
  'munch',
  null,
  4,
  true,
  '{"import_type": "wikibooks_cookbook", "original_title": "Aadun (Nigerian Corn Flour with Palm Oil)", "servings_text": null, "prep_time": null, "cook_time": null, "total_time": null, "source_dataset": "Wikibooks Cookbook", "source_url": "https://en.wikibooks.org/wiki/Cookbook:Aadun_(Nigerian_Corn_Flour_with_Palm_Oil)", "raw_tags": ["cs1 maint numeric names authors list", "with images", "easy", "without servings", "without cooking time", "yoruba", "chile", "corn flour", "palm oil", "salt"], "normalized_app_tags": ["cs1 maint numeric names authors list", "with images", "easy", "without servings", "without cooking time", "yoruba", "chile", "corn flour", "palm oil", "salt", "lunch", "spicy"], "chef_profile_url": "/chef/e280c6c4-4c73-4085-9851-634f69bc7e68"}'::jsonb
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower('Aadun (Nigerian Corn Flour with Palm Oil)')
     or (
       'https://en.wikibooks.org/wiki/Cookbook:Aadun_(Nigerian_Corn_Flour_with_Palm_Oil)' is not null
       and lower(coalesce(existing.source_url, '')) = lower('https://en.wikibooks.org/wiki/Cookbook:Aadun_(Nigerian_Corn_Flour_with_Palm_Oil)')
     )
);

insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  'Abacha Mmiri (Soaked Cassava Flakes)',
  '',
  '30 min',
  'Beginner',
  ARRAY['1 tuber of cassava', '1–2 teaspoons salt , to taste', '½ cup fresh coconut pieces', '¼ cup palm kernel', '¼ cup roasted groundnuts']::text[],
  ARRAY['very easy', 'without cooking time', 'igbo', 'cassava', 'coconut', 'salt', 'peanut', 'dinner', 'dessert', 'savory', 'fresh/citrusy']::text[],
  ARRAY['Peel the cassava, then cut into slices 1 cm thick. Rinse well.', 'Boil the cassava in a large pot of water until cooked through.', 'Soak the cooked cassava in fresh water overnight. The next day, drain away any remaining water and rinse the cassava well.', 'Season the cassava to taste with the salt.', 'Serve the cassava with the coconut, palm kernel, and roasted groundnut.']::text[],
  'community-seed',
  'e280c6c4-4c73-4085-9851-634f69bc7e68'::uuid,
  'https://en.wikibooks.org/wiki/Cookbook:Abacha_Mmiri_(Soaked_Cassava_Flakes)',
  'munch',
  null,
  1,
  true,
  '{"import_type": "wikibooks_cookbook", "original_title": "Abacha Mmiri (Soaked Cassava Flakes)", "servings_text": "1", "prep_time": null, "cook_time": null, "total_time": null, "source_dataset": "Wikibooks Cookbook", "source_url": "https://en.wikibooks.org/wiki/Cookbook:Abacha_Mmiri_(Soaked_Cassava_Flakes)", "raw_tags": ["very easy", "without cooking time", "igbo", "cassava", "coconut", "salt", "peanut"], "normalized_app_tags": ["very easy", "without cooking time", "igbo", "cassava", "coconut", "salt", "peanut", "dinner", "dessert", "savory", "fresh/citrusy"], "chef_profile_url": "/chef/e280c6c4-4c73-4085-9851-634f69bc7e68"}'::jsonb
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower('Abacha Mmiri (Soaked Cassava Flakes)')
     or (
       'https://en.wikibooks.org/wiki/Cookbook:Abacha_Mmiri_(Soaked_Cassava_Flakes)' is not null
       and lower(coalesce(existing.source_url, '')) = lower('https://en.wikibooks.org/wiki/Cookbook:Abacha_Mmiri_(Soaked_Cassava_Flakes)')
     )
);

insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  'Abuk-abuk (Sweet Steamed Sago Dumplings)',
  '',
  '30 min',
  'Advanced',
  ARRAY['120 g sago pearls', '100 g white granulated sugar', '60 g grated coconut meat', '¼ tsp salt', '½ tsp green food coloring (optional)', '8 ea. 2 cm pieces of pandan leaf', '8 banana leaves , rolled into cones']::text[],
  ARRAY['medium difficulty', 'without servings', 'without cooking time', 'steamed', 'sago', 'white sugar', 'coconut', 'salt', 'food coloring', 'pandan', 'dumpling', 'malaysian', 'banana leaf', 'lunch', 'dessert', 'sweet']::text[],
  ARRAY['Prepare a steamer over a few inches of simmering water.', 'Place the sago in a strainer , and rinse well under running water. Let drain.', 'Transfer the sago to a bowl, then mix in the coconut, salt, and food coloring.', 'Fill each banana leaf cone with a scoop of the sago mixture. It should fill the cone about halfway.', 'Place a scoop of sugar on top of the sago mixture.', 'Top the sugar with another scoop of the sago mixture.', 'Place a piece of pandan leaf on top of the sago mixture. Fold the banana leaf to fully enclose the packet.', 'Transfer the packets to the steamer, cover, and steam for 15–20 minutes.', 'Remove from the steamer and allow to cool.', 'Unwrap the packets and serve.']::text[],
  'community-seed',
  'e280c6c4-4c73-4085-9851-634f69bc7e68'::uuid,
  'https://en.wikibooks.org/wiki/Cookbook:Abuk-abuk_(Sweet_Steamed_Sago_Dumplings)',
  'munch',
  null,
  4,
  true,
  '{"import_type": "wikibooks_cookbook", "original_title": "Abuk-abuk (Sweet Steamed Sago Dumplings)", "servings_text": null, "prep_time": null, "cook_time": null, "total_time": null, "source_dataset": "Wikibooks Cookbook", "source_url": "https://en.wikibooks.org/wiki/Cookbook:Abuk-abuk_(Sweet_Steamed_Sago_Dumplings)", "raw_tags": ["medium difficulty", "without servings", "without cooking time", "steamed", "sago", "white sugar", "coconut", "salt", "food coloring", "pandan", "dumpling", "malaysian", "banana leaf"], "normalized_app_tags": ["medium difficulty", "without servings", "without cooking time", "steamed", "sago", "white sugar", "coconut", "salt", "food coloring", "pandan", "dumpling", "malaysian", "banana leaf", "lunch", "dessert", "sweet"], "chef_profile_url": "/chef/e280c6c4-4c73-4085-9851-634f69bc7e68"}'::jsonb
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower('Abuk-abuk (Sweet Steamed Sago Dumplings)')
     or (
       'https://en.wikibooks.org/wiki/Cookbook:Abuk-abuk_(Sweet_Steamed_Sago_Dumplings)' is not null
       and lower(coalesce(existing.source_url, '')) = lower('https://en.wikibooks.org/wiki/Cookbook:Abuk-abuk_(Sweet_Steamed_Sago_Dumplings)')
     )
);

insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  'Accra Cassava (Cameroonian Cassava Fritters)',
  '',
  '30 min',
  'Intermediate',
  ARRAY['3 pounds grated cassava (can be frozen and thawed)', '4 large, overly ripe bananas (optional)', '1 teaspoon or more of salt', 'A good amount of vegetable oil']::text[],
  ARRAY['fritter', 'medium difficulty', 'without servings', 'without cooking time', 'cameroonian', 'fritters', 'fried', 'cassava', 'banana', 'vegetable oil', 'lunch', 'spicy', 'fresh/citrusy']::text[],
  ARRAY['Squeeze the grated cassava using a kitchen cloth or cheesecloth (like the one used for preparing homemade pap) to remove as much liquid as possible. The cassava should be very dry with little liquid.', 'Mash the bananas well using a fork, masher , or food processor .', 'Add the cassava and salt to the mashed banana in a medium sized bowl, and mix them together very well. The mixture should be firm enough that it can be rolled into balls.', 'Use your palms to roll about 2 tablespoons of the mixture into bite-size balls.', 'Heat the vegetable oil to 375 °F in a deep skillet or a saucepan . You can check the oil temperature by dropping in a 1- inch square of bread—it should take about 1 minute to brown.', 'Place the cassava balls gently into the hot oil and fry until golden brown. Do not overcrowd the pan—work in batches as necessary.', 'Remove the fritters from the hot oil, drain, and serve fresh.']::text[],
  'community-seed',
  'e280c6c4-4c73-4085-9851-634f69bc7e68'::uuid,
  'https://en.wikibooks.org/wiki/Cookbook:Accra_Cassava_(Cameroonian_Cassava_Fritters)',
  'munch',
  null,
  4,
  true,
  '{"import_type": "wikibooks_cookbook", "original_title": "Accra Cassava (Cameroonian Cassava Fritters)", "servings_text": null, "prep_time": null, "cook_time": null, "total_time": null, "source_dataset": "Wikibooks Cookbook", "source_url": "https://en.wikibooks.org/wiki/Cookbook:Accra_Cassava_(Cameroonian_Cassava_Fritters)", "raw_tags": ["fritter", "medium difficulty", "without servings", "without cooking time", "cameroonian", "fritters", "fried", "cassava", "banana", "vegetable oil"], "normalized_app_tags": ["fritter", "medium difficulty", "without servings", "without cooking time", "cameroonian", "fritters", "fried", "cassava", "banana", "vegetable oil", "lunch", "spicy", "fresh/citrusy"], "chef_profile_url": "/chef/e280c6c4-4c73-4085-9851-634f69bc7e68"}'::jsonb
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower('Accra Cassava (Cameroonian Cassava Fritters)')
     or (
       'https://en.wikibooks.org/wiki/Cookbook:Accra_Cassava_(Cameroonian_Cassava_Fritters)' is not null
       and lower(coalesce(existing.source_url, '')) = lower('https://en.wikibooks.org/wiki/Cookbook:Accra_Cassava_(Cameroonian_Cassava_Fritters)')
     )
);

insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  'Acid Drops',
  '',
  '30 min',
  'Intermediate',
  ARRAY['2 cups (480 mL ) white granulated sugar', '1 cup (240 mL) water', '½ tsp (2.5 mL) cream of tartar', '1 Tbsp (15 mL) citric acid', 'Powdered sugar']::text[],
  ARRAY['confection', 'medium difficulty', 'without servings', 'confections', 'english', 'granulated sugar', 'citric acid', 'cream of tartar', 'dessert', 'sweet']::text[],
  ARRAY['Bring the sugar, water and cream of tartar to boil over medium-low heat. Stir gently until syrup reaches 310°F (155°C/hard crack stage) or is pale brown. Syrup should harden completely when dropped on to a cold plate and snap between the teeth when cold.', 'Pour the mixture onto an oiled heatproof work surface, and sprinkle with the citric acid.', 'Use a greased spatula to fold in the sides and thoroughly work the acid in.', 'When the candy is cool enough to touch but still pliable, roll it into sticks and snip off drop-sized bits.', 'Sift powdered sugar onto the candies, and shake to coat.', 'Allow to cool and harden completely. Store in an air-tight container.']::text[],
  'community-seed',
  'e280c6c4-4c73-4085-9851-634f69bc7e68'::uuid,
  'https://en.wikibooks.org/wiki/Cookbook:Acid_Drops',
  'munch',
  null,
  4,
  true,
  '{"import_type": "wikibooks_cookbook", "original_title": "Acid Drops", "servings_text": null, "prep_time": null, "cook_time": null, "total_time": null, "source_dataset": "Wikibooks Cookbook", "source_url": "https://en.wikibooks.org/wiki/Cookbook:Acid_Drops", "raw_tags": ["confection", "medium difficulty", "without servings", "confections", "english", "granulated sugar", "citric acid", "cream of tartar"], "normalized_app_tags": ["confection", "medium difficulty", "without servings", "confections", "english", "granulated sugar", "citric acid", "cream of tartar", "dessert", "sweet"], "chef_profile_url": "/chef/e280c6c4-4c73-4085-9851-634f69bc7e68"}'::jsonb
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower('Acid Drops')
     or (
       'https://en.wikibooks.org/wiki/Cookbook:Acid_Drops' is not null
       and lower(coalesce(existing.source_url, '')) = lower('https://en.wikibooks.org/wiki/Cookbook:Acid_Drops')
     )
);

insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  'Acorn Crusted Salmon',
  '',
  '30 min',
  'Beginner',
  ARRAY['2 salmon fillets', '1½ cups (320 ml ) of shelled acorns', '2 egg whites']::text[],
  ARRAY['with images', 'medium difficulty', 'without cooking time', 'acorn', 'egg white', 'salmon', 'breakfast', 'dinner']::text[],
  ARRAY['Use a food processor, blender or other method (meat tenderizer, etc.) to pulverize the acorns into a fine meal. If desired, toast the acorn meal for 5-7 minutes at 375°F/190°C/gas mark 5. Transfer the acorn meal to a dish.', 'Place the egg whites in a shallow dish. Coat each salmon fillet in egg white.', 'Coat each fillet with the acorn meal.']::text[],
  'community-seed',
  'e280c6c4-4c73-4085-9851-634f69bc7e68'::uuid,
  'https://en.wikibooks.org/wiki/Cookbook:Acorn_Crusted_Salmon',
  'munch',
  null,
  2,
  true,
  '{"import_type": "wikibooks_cookbook", "original_title": "Acorn Crusted Salmon", "servings_text": "2 servings", "prep_time": null, "cook_time": null, "total_time": null, "source_dataset": "Wikibooks Cookbook", "source_url": "https://en.wikibooks.org/wiki/Cookbook:Acorn_Crusted_Salmon", "raw_tags": ["with images", "medium difficulty", "without cooking time", "acorn", "egg white", "salmon"], "normalized_app_tags": ["with images", "medium difficulty", "without cooking time", "acorn", "egg white", "salmon", "breakfast", "dinner"], "chef_profile_url": "/chef/e280c6c4-4c73-4085-9851-634f69bc7e68"}'::jsonb
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower('Acorn Crusted Salmon')
     or (
       'https://en.wikibooks.org/wiki/Cookbook:Acorn_Crusted_Salmon' is not null
       and lower(coalesce(existing.source_url, '')) = lower('https://en.wikibooks.org/wiki/Cookbook:Acorn_Crusted_Salmon')
     )
);

insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  'Acorn Squash with Orange Marmalade',
  '',
  '30 min',
  'Intermediate',
  ARRAY['1 medium acorn squash , halved lengthwise', '1 tablespoon orange marmalade', '1 teaspoon butter or margarine', '⅛ teaspoon salt']::text[],
  ARRAY['squash', 'easy', 'north american', 'inexpensive', 'baked', 'broiled', 'acorn squash', 'butter', 'margarine', 'marmalade', 'american', 'lunch', 'dinner', 'dessert']::text[],
  ARRAY['Preheat oven to 400°F (204°C).', 'Remove seeds and strings from squash halves.', 'Cut a small piece off outside of each half to make a flat space on which the half can stand level.', 'Place halves in a shallow pan or casserole in ¼ inch (6 mm) water with insides facing down. Bake for 35 minutes.', 'Combine marmalade and butter in a small bowl.', 'Remove squash from oven, and invert in pan or dish. Salt lightly.', 'Spread marmalade and butter mixture on edges of squash, allowing excess to run into center.', 'Place under broiler for 5 minutes or until lightly browned.']::text[],
  'community-seed',
  'e280c6c4-4c73-4085-9851-634f69bc7e68'::uuid,
  'https://en.wikibooks.org/wiki/Cookbook:Acorn_Squash_with_Orange_Marmalade',
  'munch',
  'American',
  2,
  true,
  '{"import_type": "wikibooks_cookbook", "original_title": "Acorn Squash with Orange Marmalade", "servings_text": "2", "prep_time": null, "cook_time": null, "total_time": null, "source_dataset": "Wikibooks Cookbook", "source_url": "https://en.wikibooks.org/wiki/Cookbook:Acorn_Squash_with_Orange_Marmalade", "raw_tags": ["squash", "easy", "north american", "inexpensive", "baked", "broiled", "acorn squash", "butter", "margarine", "marmalade"], "normalized_app_tags": ["squash", "easy", "north american", "inexpensive", "baked", "broiled", "acorn squash", "butter", "margarine", "marmalade", "american", "lunch", "dinner", "dessert"], "chef_profile_url": "/chef/e280c6c4-4c73-4085-9851-634f69bc7e68"}'::jsonb
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower('Acorn Squash with Orange Marmalade')
     or (
       'https://en.wikibooks.org/wiki/Cookbook:Acorn_Squash_with_Orange_Marmalade' is not null
       and lower(coalesce(existing.source_url, '')) = lower('https://en.wikibooks.org/wiki/Cookbook:Acorn_Squash_with_Orange_Marmalade')
     )
);

insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  'Adobo Chicken (Philippine)',
  '',
  '30 min',
  'Intermediate',
  ARRAY['6–8 chicken pieces, preferably legs and wings', '⅓ cup (80 ml ) vinegar made from coconut juice (as a variant, try balsamic vinegar)', '¼ cup (60 ml) soy sauce', '4 cloves of garlic , crushed', '1–2 bay leaves', '½ tsp (2.5 ml) freshly cracked (not ground) black peppercorns']::text[],
  ARRAY['filipino', 'with images', 'medium difficulty', 'without servings', 'without cooking time', 'chicken', 'slow cooker', 'naturally gluten-free', 'with metric units', 'bay leaf', 'garlic', 'dessert', 'snack', 'spicy', 'savory', 'umami', 'fresh/citrusy', 'gluten-free']::text[],
  ARRAY['Put chicken, garlic, peppercorn, soy sauce and vinegar in a pan and bring to a boil.', 'When chicken is cooked, put chicken pieces in a colander and drain. Put aside the pot with soy sauce and vinegar.', 'When chicken pieces are no longer draining, fry them in hot oil at medium heat. Have a cover ready for splatters.', 'Sear the chicken, browning on all sides.', 'Put chicken pieces back in the pot with soy sauce and vinegar and bring to simmer. Add 1–2 pieces of bay leaf.', 'Cook until the sauce has largely evaporated; some take this to an extreme and cook until the sauce has thickened and adhered to the chicken, which begins to make a popping noise due to the high, direct heat.', 'Serve over hot steamed rice. May be eaten with tomato slices in fish sauce, tapsilog, soy sauce, vinegar, hotdog, etc.']::text[],
  'community-seed',
  'e280c6c4-4c73-4085-9851-634f69bc7e68'::uuid,
  'https://en.wikibooks.org/wiki/Cookbook:Adobo_Chicken_(Philippine)',
  'munch',
  null,
  4,
  true,
  '{"import_type": "wikibooks_cookbook", "original_title": "Adobo Chicken (Philippine)", "servings_text": null, "prep_time": null, "cook_time": null, "total_time": null, "source_dataset": "Wikibooks Cookbook", "source_url": "https://en.wikibooks.org/wiki/Cookbook:Adobo_Chicken_(Philippine)", "raw_tags": ["filipino", "with images", "medium difficulty", "without servings", "without cooking time", "chicken", "slow cooker", "naturally gluten-free", "with metric units", "bay leaf", "garlic"], "normalized_app_tags": ["filipino", "with images", "medium difficulty", "without servings", "without cooking time", "chicken", "slow cooker", "naturally gluten-free", "with metric units", "bay leaf", "garlic", "dessert", "snack", "spicy", "savory", "umami", "fresh/citrusy", "gluten-free"], "chef_profile_url": "/chef/e280c6c4-4c73-4085-9851-634f69bc7e68"}'::jsonb
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower('Adobo Chicken (Philippine)')
     or (
       'https://en.wikibooks.org/wiki/Cookbook:Adobo_Chicken_(Philippine)' is not null
       and lower(coalesce(existing.source_url, '')) = lower('https://en.wikibooks.org/wiki/Cookbook:Adobo_Chicken_(Philippine)')
     )
);

insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  'Adobo Sauce',
  '',
  '30 min',
  'Beginner',
  ARRAY['12 chipotle peppers or smoked, dried jalapeño peppers (most co-ops can get these for you, or try the specialty produce section of your grocery store)', '4 cups (0.95 L ) water', '½ cup (120 ml ) onion , diced', '⅓ cup (80 ml) apple cider vinegar', '¼ cup (60 ml) ketchup', '3 cloves garlic , crushed or sliced', '1 pinch of cumin , oregano', 'Salt to taste']::text[],
  ARRAY['sauce', 'easy', 'without servings', 'without cooking time', 'mexican', 'tex-mex', 'southwestern', 'chipotle chile', 'sauces and condiments', 'slow cooker', 'with metric units', 'jalape o chile', 'garlic', 'cumin', 'ketchup', 'dinner', 'savory']::text[],
  ARRAY['Combine all ingredients in a heavy saucepan . Cook over a very low heat for 1–2 hours until the chiles are very soft and the liquid has been reduced to about 1 cup. Alternatively, cook in a slow cooker overnight.', 'Beat with a mortar and pestle , or put in blender to puree for a thick sauce.']::text[],
  'community-seed',
  'e280c6c4-4c73-4085-9851-634f69bc7e68'::uuid,
  'https://en.wikibooks.org/wiki/Cookbook:Adobo_Sauce',
  'munch',
  'Mexican',
  4,
  true,
  '{"import_type": "wikibooks_cookbook", "original_title": "Adobo Sauce", "servings_text": null, "prep_time": null, "cook_time": null, "total_time": null, "source_dataset": "Wikibooks Cookbook", "source_url": "https://en.wikibooks.org/wiki/Cookbook:Adobo_Sauce", "raw_tags": ["sauce", "easy", "without servings", "without cooking time", "mexican", "tex-mex", "southwestern", "chipotle chile", "sauces and condiments", "slow cooker", "with metric units", "jalape o chile", "garlic", "cumin", "ketchup"], "normalized_app_tags": ["sauce", "easy", "without servings", "without cooking time", "mexican", "tex-mex", "southwestern", "chipotle chile", "sauces and condiments", "slow cooker", "with metric units", "jalape o chile", "garlic", "cumin", "ketchup", "dinner", "savory"], "chef_profile_url": "/chef/e280c6c4-4c73-4085-9851-634f69bc7e68"}'::jsonb
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower('Adobo Sauce')
     or (
       'https://en.wikibooks.org/wiki/Cookbook:Adobo_Sauce' is not null
       and lower(coalesce(existing.source_url, '')) = lower('https://en.wikibooks.org/wiki/Cookbook:Adobo_Sauce')
     )
);

insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  'Adoyo (Nigerian Ogi Beverage)',
  '',
  '30 min',
  'Beginner',
  ARRAY['Ogi water', 'Ripe pineapple , sliced', 'Fresh or dried lemongrass leaves, rinsed', 'Lemons or oranges', 'White sugar']::text[],
  ARRAY['beverage', 'medium difficulty', 'without servings', 'without cooking time', 'caramel', 'beverages', 'nigerian', 'pineapple', 'white sugar', 'lemongrass', 'dessert', 'spicy', 'sweet', 'fresh/citrusy']::text[],
  ARRAY['Combine ogi water, pineapple, and lemongrass leaves in a pot. Simmer for at least 45 minutes.', 'Remove from the heat, and cool completely. Once cool, strain out the solids.', 'Place the sugar in a pot. Slowly melt it over medium heat, stirring, and cook until it reaches a light brown caramel.', 'Stir some hot water into the caramel to make a sauce—if you use cold water, it will crystallize. Set aside.', 'Sweeten the strained liquid with the caramel sauce, and serve.']::text[],
  'community-seed',
  'e280c6c4-4c73-4085-9851-634f69bc7e68'::uuid,
  'https://en.wikibooks.org/wiki/Cookbook:Adoyo_(Nigerian_Ogi_Beverage)',
  'munch',
  null,
  4,
  true,
  '{"import_type": "wikibooks_cookbook", "original_title": "Adoyo (Nigerian Ogi Beverage)", "servings_text": null, "prep_time": null, "cook_time": null, "total_time": null, "source_dataset": "Wikibooks Cookbook", "source_url": "https://en.wikibooks.org/wiki/Cookbook:Adoyo_(Nigerian_Ogi_Beverage)", "raw_tags": ["beverage", "medium difficulty", "without servings", "without cooking time", "caramel", "beverages", "nigerian", "pineapple", "white sugar", "lemongrass"], "normalized_app_tags": ["beverage", "medium difficulty", "without servings", "without cooking time", "caramel", "beverages", "nigerian", "pineapple", "white sugar", "lemongrass", "dessert", "spicy", "sweet", "fresh/citrusy"], "chef_profile_url": "/chef/e280c6c4-4c73-4085-9851-634f69bc7e68"}'::jsonb
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower('Adoyo (Nigerian Ogi Beverage)')
     or (
       'https://en.wikibooks.org/wiki/Cookbook:Adoyo_(Nigerian_Ogi_Beverage)' is not null
       and lower(coalesce(existing.source_url, '')) = lower('https://en.wikibooks.org/wiki/Cookbook:Adoyo_(Nigerian_Ogi_Beverage)')
     )
);

insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  'Adult Macaroni and Cheese',
  '',
  '30 min',
  'Intermediate',
  ARRAY['½ pound (227 g ) elbow macaroni', '6 ounces (170 g) heavy cream', '½ tsp (2.5 ml ) kosher salt , plus more for the water', '½ cup (60 g / 2.1 oz ) grated Fontina', '½ cup (60 g / 2.1 oz) grated Gruyere', '½ cup (150 g / 5.3 oz) mascarpone cheese', '½ cup (150 g / 5.3 oz) cream cheese', '4 thin slices Swiss cheese , julienned', '1¼ sticks (150 g / 5.3 oz) unsalted butter , divided', '2 tbsp (30 ml) all-purpose flour', '1 tsp (5 ml) tabasco sauce']::text[],
  ARRAY['pasta', 'medium difficulty', 'gruy re', 'pasta and noodles', 'main course', 'side dish', 'boiled', 'with metric units', 'butter', 'macaroni and cheese', 'mascarpone', 'cream cheese', 'emmental', 'fontina', 'united states', 'heavy cream', 'swiss cheese', 'all-purpose flour', 'dinner']::text[],
  ARRAY['In a gallon (~3.8 L) of salted boiling water, cook macaroni to al dente . Strain into a colander and rinse with cold water.', 'While pasta is cooking, in a heavy saucepan , melt 2 tbsp butter over medium heat. Once bubbling ceases, whisk in flour and cook, whisking continuously, until blonde.', 'Add remaining ingredients except butter. Once cheese is melted and sauce is smooth, add 1 tbsp butter, whisking continuously until melted. Repeat until all butter has been used.', 'Gently fold in macaroni and serve warm.']::text[],
  'community-seed',
  'e280c6c4-4c73-4085-9851-634f69bc7e68'::uuid,
  'https://en.wikibooks.org/wiki/Cookbook:Adult_Macaroni_and_Cheese',
  'munch',
  null,
  4,
  true,
  '{"import_type": "wikibooks_cookbook", "original_title": "Adult Macaroni and Cheese", "servings_text": "4", "prep_time": null, "cook_time": null, "total_time": null, "source_dataset": "Wikibooks Cookbook", "source_url": "https://en.wikibooks.org/wiki/Cookbook:Adult_Macaroni_and_Cheese", "raw_tags": ["pasta", "medium difficulty", "gruy re", "pasta and noodles", "main course", "side dish", "boiled", "with metric units", "butter", "macaroni and cheese", "mascarpone", "cream cheese", "emmental", "fontina", "united states", "heavy cream", "swiss cheese", "all-purpose flour"], "normalized_app_tags": ["pasta", "medium difficulty", "gruy re", "pasta and noodles", "main course", "side dish", "boiled", "with metric units", "butter", "macaroni and cheese", "mascarpone", "cream cheese", "emmental", "fontina", "united states", "heavy cream", "swiss cheese", "all-purpose flour", "dinner"], "chef_profile_url": "/chef/e280c6c4-4c73-4085-9851-634f69bc7e68"}'::jsonb
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower('Adult Macaroni and Cheese')
     or (
       'https://en.wikibooks.org/wiki/Cookbook:Adult_Macaroni_and_Cheese' is not null
       and lower(coalesce(existing.source_url, '')) = lower('https://en.wikibooks.org/wiki/Cookbook:Adult_Macaroni_and_Cheese')
     )
);

commit;
