#!/usr/bin/env python3
"""
Convert normalized recipe JSONL into idempotent SQL inserts for public.recipes.

Intended for importing datasets such as the Wikibooks Cookbook export generated by
scripts/import_wikibooks_cookbook.py.

Usage:
    python scripts/jsonl_to_recipes_sql.py \
        --input data/wikibooks_cookbook_recipes.jsonl \
        --output data/wikibooks_cookbook_recipes.sql \
        --source imported \
        --chef "Wikibooks Cookbook"
"""

from __future__ import annotations

import argparse
import json
import os
import re
from typing import Any, Dict, Iterable, List, Optional

MEAL_KEYWORDS = {
    "breakfast": [
        "bagel", "breakfast", "brunch", "cereal", "crepe", "egg", "french toast",
        "granola", "hash brown", "muffin", "oatmeal", "omelet", "omelette",
        "pancake", "porridge", "smoothie", "toast", "waffle",
    ],
    "lunch": [
        "bowl", "burger", "club", "grain bowl", "lunch", "panini", "pita",
        "quesadilla", "salad", "sandwich", "soup", "sub", "taco", "wrap",
    ],
    "dinner": [
        "baked", "biryani", "braised", "casserole", "curry", "dinner", "enchilada",
        "fillet", "grilled", "lasagna", "meatloaf", "paella", "pasta", "pho",
        "ramen", "risotto", "roast", "stew", "stir fry", "stir-fry", "teriyaki",
        "tikka masala",
    ],
    "dessert": [
        "brownie", "cake", "cheesecake", "cobbler", "cookie", "cupcake", "dessert",
        "doughnut", "donut", "fudge", "ice cream", "mousse", "pie", "pudding",
        "sorbet", "sweet", "tart", "tiramisu",
    ],
    "snack": [
        "appetizer", "bruschetta", "chips", "dip", "finger food", "hummus", "nachos",
        "popcorn", "snack", "spring roll", "trail mix", "wings",
    ],
}

FLAVOR_KEYWORDS = {
    "spicy": ["buffalo", "cayenne", "chili", "chilli", "curry", "habanero", "hot", "jalapeno", "pepper flakes", "sriracha", "spicy"],
    "sweet": ["cake", "caramel", "chocolate", "dessert", "honey", "maple", "sweet", "syrup", "vanilla"],
    "savory": ["garlic", "onion", "roasted", "savory", "savoury", "soy sauce", "stock"],
    "umami": ["anchovy", "miso", "mushroom", "parmesan", "soy sauce", "tamari", "umami"],
    "fresh/citrusy": ["citrus", "fresh", "lemon", "lime", "orange zest", "vinaigrette", "yuzu"],
}

EXPLICIT_DIETARY_KEYWORDS = {
    "vegetarian": ["vegetarian"],
    "vegan": ["vegan"],
    "gluten-free": ["gluten free", "gluten-free"],
    "dairy-free": ["dairy free", "dairy-free"],
    "nut-free": ["nut free", "nut-free"],
}

NOISY_TAG_PREFIXES = (
    "cookbook",
    "recipe",
    "recipes",
    "wikibooks",
)


def ensure_parent_dir(path: str) -> None:
    parent = os.path.dirname(os.path.abspath(path))
    if parent:
        os.makedirs(parent, exist_ok=True)


def sql_quote(value: Optional[str]) -> str:
    if value is None:
        return "null"
    return "'" + str(value).replace("\\", "\\\\").replace("'", "''") + "'"


def sql_jsonb(value: Any) -> str:
    return sql_quote(json.dumps(value, ensure_ascii=False)) + "::jsonb"


def sql_text_array(values: Iterable[str]) -> str:
    cleaned = [sql_quote(str(value)) for value in values if str(value).strip()]
    return f"ARRAY[{', '.join(cleaned)}]::text[]"


def clean_text(value: Any) -> str:
    text = str(value or "")
    text = text.replace("\xa0", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def slugify_tag(value: str) -> str:
    value = clean_text(value).lower()
    value = value.replace("_", " ")
    value = value.replace("&", " and ")
    value = re.sub(r"[^a-z0-9+/ -]", " ", value)
    value = re.sub(r"\s+", " ", value).strip()
    return value


def contains_keyword(haystack: str, keywords: Iterable[str]) -> bool:
    return any(keyword in haystack for keyword in keywords)


def infer_meal_tags(search_text: str) -> List[str]:
    meal_tags = [meal for meal, keywords in MEAL_KEYWORDS.items() if contains_keyword(search_text, keywords)]
    return meal_tags or ["dinner"]


def infer_flavor_tags(search_text: str) -> List[str]:
    return [flavor for flavor, keywords in FLAVOR_KEYWORDS.items() if contains_keyword(search_text, keywords)]


def infer_dietary_tags(search_text: str) -> List[str]:
    return [tag for tag, keywords in EXPLICIT_DIETARY_KEYWORDS.items() if contains_keyword(search_text, keywords)]


def infer_difficulty(cook_time: str, ingredient_count: int, instruction_count: int) -> str:
    minutes = 0
    minute_match = re.findall(r"(\d+)\s*(?:hour|hours|hr|hrs|minute|minutes|min)", cook_time.lower())
    if minute_match:
        minutes = sum(int(part) for part in minute_match)

    if minutes >= 90 or ingredient_count >= 14 or instruction_count >= 10:
        return "Advanced"
    if minutes >= 40 or ingredient_count >= 9 or instruction_count >= 6:
        return "Intermediate"
    return "Beginner"


def infer_cuisine(tags: List[str], title: str) -> Optional[str]:
    values = [tag.lower() for tag in tags] + [title.lower()]
    joined = " ".join(values)

    cuisine_map = {
        "american": "American",
        "british": "British",
        "chinese": "Chinese",
        "french": "French",
        "greek": "Greek",
        "indian": "Indian",
        "italian": "Italian",
        "japanese": "Japanese",
        "korean": "Korean",
        "mediterranean": "Mediterranean",
        "mexican": "Mexican",
        "middle eastern": "Middle Eastern",
        "thai": "Thai",
        "vietnamese": "Vietnamese",
    }

    for needle, label in cuisine_map.items():
        if needle in joined:
            return label
    return None


def infer_servings(raw_value: Any) -> int:
    text = clean_text(raw_value)
    if not text:
        return 4
    match = re.search(r"(\d+)", text)
    if not match:
        return 4
    value = int(match.group(1))
    return value if value > 0 else 4


def normalize_tags(raw_tags: Any) -> List[str]:
    if not isinstance(raw_tags, list):
        return []
    tags = []
    for tag in raw_tags:
        normalized = slugify_tag(tag)
        if normalized:
            normalized = re.sub(r"^(?:for|using)\s+", "", normalized)
            normalized = re.sub(r"\s+recipes?$", "", normalized)
            normalized = re.sub(r"\s+", " ", normalized).strip()
            if not normalized:
                continue
            if any(normalized == prefix or normalized.startswith(f"{prefix} ") for prefix in NOISY_TAG_PREFIXES):
                continue
            tags.append(normalized)
    return list(dict.fromkeys(tags))


def build_app_tags(recipe: Dict[str, Any], cuisine: Optional[str]) -> List[str]:
    title = clean_text(recipe.get("title"))
    ingredients = [clean_text(item) for item in recipe.get("ingredients", []) if clean_text(item)]
    instructions = [clean_text(item) for item in recipe.get("instructions", []) if clean_text(item)]
    raw_tags = normalize_tags(recipe.get("tags", []))

    search_text = " ".join(
        [title.lower(), " ".join(raw_tags), " ".join(item.lower() for item in ingredients), " ".join(step.lower() for step in instructions)]
    )

    tags: List[str] = []
    tags.extend(raw_tags)
    if cuisine:
        tags.append(cuisine.lower())
    tags.extend(infer_meal_tags(search_text))
    tags.extend(infer_flavor_tags(search_text))
    tags.extend(infer_dietary_tags(search_text))

    if "appetizer" in raw_tags and "snack" not in tags:
        tags.append("snack")
    if "dessert" in raw_tags and "sweet" not in tags:
        tags.append("sweet")

    return list(dict.fromkeys(tag for tag in tags if tag))


def build_insert_sql(
    recipe: Dict[str, Any],
    source: str,
    chef: Optional[str],
    created_by: Optional[str],
    is_public: bool,
    chef_profile_url: Optional[str],
) -> Optional[str]:
    title = clean_text(recipe.get("title"))
    ingredients = [clean_text(item) for item in recipe.get("ingredients", []) if clean_text(item)]
    instructions = [clean_text(item) for item in recipe.get("instructions", []) if clean_text(item)]
    source_url = clean_text(recipe.get("source_url"))

    if len(title) == 0 or len(ingredients) < 2 or len(instructions) < 1:
        return None

    prep_time = clean_text(recipe.get("prep_time"))
    cook_time = clean_text(recipe.get("cook_time"))
    total_time = clean_text(recipe.get("total_time"))
    cook_time_value = total_time or " + ".join(part for part in [prep_time, cook_time] if part) or "30 min"
    servings = infer_servings(recipe.get("servings"))
    raw_tags = normalize_tags(recipe.get("tags", []))
    cuisine = infer_cuisine(raw_tags, title)
    tags = build_app_tags(recipe, cuisine)
    difficulty = infer_difficulty(cook_time_value, len(ingredients), len(instructions))

    raw_payload = {
        "import_type": "wikibooks_cookbook",
        "original_title": recipe.get("title"),
        "servings_text": recipe.get("servings"),
        "prep_time": recipe.get("prep_time"),
        "cook_time": recipe.get("cook_time"),
        "total_time": recipe.get("total_time"),
        "source_dataset": "Wikibooks Cookbook",
        "source_url": source_url or None,
        "raw_tags": raw_tags,
        "normalized_app_tags": tags,
        "chef_profile_url": chef_profile_url,
    }

    created_by_sql = f"{sql_quote(created_by)}::uuid" if created_by else "null"
    chef_sql = sql_quote(chef) if chef else "null"
    source_url_sql = sql_quote(source_url) if source_url else "null"
    cuisine_sql = sql_quote(cuisine) if cuisine else "null"
    public_sql = "true" if is_public else "false"

    dedupe_title = sql_quote(title)
    dedupe_source_url = sql_quote(source_url) if source_url else "null"

    return f"""insert into public.recipes (
  name,
  image,
  cook_time,
  difficulty,
  ingredients,
  tags,
  instructions,
  source,
  created_by,
  source_url,
  chef,
  cuisine,
  servings,
  is_public,
  raw_api_payload
)
select
  {sql_quote(title)},
  '',
  {sql_quote(cook_time_value)},
  {sql_quote(difficulty)},
  {sql_text_array(ingredients)},
  {sql_text_array(tags)},
  {sql_text_array(instructions)},
  {sql_quote(source)},
  {created_by_sql},
  {source_url_sql},
  {chef_sql},
  {cuisine_sql},
  {servings},
  {public_sql},
  {sql_jsonb(raw_payload)}
where not exists (
  select 1
  from public.recipes existing
  where lower(existing.name) = lower({dedupe_title})
     or (
       {dedupe_source_url} is not null
       and lower(coalesce(existing.source_url, '')) = lower({dedupe_source_url})
     )
);"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Convert recipe JSONL into SQL inserts for public.recipes.")
    parser.add_argument("--input", required=True, help="Input JSONL file.")
    parser.add_argument("--output", required=True, help="Output SQL file.")
    parser.add_argument("--source", default="imported", help="Value for recipes.source.")
    parser.add_argument("--chef", default="Wikibooks Cookbook", help="Value for recipes.chef.")
    parser.add_argument("--created-by", default=None, help="Optional UUID for recipes.created_by.")
    parser.add_argument("--chef-profile-url", default=None, help="Optional chef profile URL to embed in raw_api_payload.")
    parser.add_argument("--public", dest="is_public", action="store_true", default=True, help="Mark inserted recipes public.")
    parser.add_argument("--private", dest="is_public", action="store_false", help="Mark inserted recipes private.")
    args = parser.parse_args()

    ensure_parent_dir(args.output)

    inserts: List[str] = []
    total = 0
    skipped = 0

    with open(args.input, "r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            total += 1

            try:
                recipe = json.loads(line)
            except json.JSONDecodeError:
                skipped += 1
                continue

            statement = build_insert_sql(
                recipe=recipe,
                source=args.source,
                chef=args.chef,
                created_by=args.created_by,
                is_public=args.is_public,
                chef_profile_url=args.chef_profile_url,
            )
            if statement:
                inserts.append(statement)
            else:
                skipped += 1

    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write("-- Generated by scripts/jsonl_to_recipes_sql.py\n")
        handle.write(f"-- Source JSONL: {args.input}\n\n")
        handle.write("begin;\n\n")
        for statement in inserts:
            handle.write(statement)
            handle.write("\n\n")
        handle.write("commit;\n")

    print(
        f"Wrote {len(inserts)} insert statements to {args.output} "
        f"(processed={total}, skipped={skipped})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
